// <auto-generated />
using System;
using GestionReservasHotelAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionReservasHotelAPI.Migrations
{
    [DbContext(typeof(GestionReservasHotelContext))]
    [Migration("20240719214345_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionReservasHotelAPI.Database.Entities.AdditionalServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("additional_sevices", "dbo");
                });

            modelBuilder.Entity("GestionReservasHotelAPI.Database.Entities.AdditionalServiceReservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AdditionalServiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("additional_service_id");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reservation_id");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalServiceId");

                    b.HasIndex("ReservationId");

                    b.ToTable("additional_services_reservations", "dbo");
                });

            modelBuilder.Entity("GestionReservasHotelAPI.Database.Entities.HotelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("NumberPhone")
                        .HasColumnType("int")
                        .HasColumnName("number_phone");

                    b.Property<int>("StarsMichelin")
                        .HasColumnType("int")
                        .HasColumnName("stars_michelin");

                    b.HasKey("Id");

                    b.ToTable("hotels", "dbo");
                });

            modelBuilder.Entity("GestionReservasHotelAPI.Database.Entities.ReservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("client_id");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("condition");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("finish_date");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("reservations", "dbo");
                });

            modelBuilder.Entity("GestionReservasHotelAPI.Database.Entities.RoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("condition");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("hotel_id");

                    b.Property<int>("NumberRoom")
                        .HasColumnType("int")
                        .HasColumnName("number_room");

                    b.Property<double>("PriceNight")
                        .HasColumnType("float")
                        .HasColumnName("price_night");

                    b.Property<string>("TypeRoom")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type_room");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("rooms", "dbo");
                });

            modelBuilder.Entity("GestionReservasHotelAPI.Database.Entities.RoomReservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("RoomId");

                    b.ToTable("rooms_reservations", "dbo");
                });

            modelBuilder.Entity("GestionReservasHotelAPI.Database.Entities.AdditionalServiceEntity", b =>
                {
                    b.HasOne("GestionReservasHotelAPI.Database.Entities.HotelEntity", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("GestionReservasHotelAPI.Database.Entities.AdditionalServiceReservationEntity", b =>
                {
                    b.HasOne("GestionReservasHotelAPI.Database.Entities.AdditionalServiceEntity", "AdditionalService")
                        .WithMany("Reservations")
                        .HasForeignKey("AdditionalServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionReservasHotelAPI.Database.Entities.ReservationEntity", "Reservation")
                        .WithMany("AdditionalServices")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdditionalService");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("GestionReservasHotelAPI.Database.Entities.RoomEntity", b =>
                {
                    b.HasOne("GestionReservasHotelAPI.Database.Entities.HotelEntity", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("GestionReservasHotelAPI.Database.Entities.RoomReservationEntity", b =>
                {
                    b.HasOne("GestionReservasHotelAPI.Database.Entities.ReservationEntity", "Reservation")
                        .WithMany("Rooms")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionReservasHotelAPI.Database.Entities.RoomEntity", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("GestionReservasHotelAPI.Database.Entities.AdditionalServiceEntity", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("GestionReservasHotelAPI.Database.Entities.ReservationEntity", b =>
                {
                    b.Navigation("AdditionalServices");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("GestionReservasHotelAPI.Database.Entities.RoomEntity", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
